<a href="https://colab.research.google.com/github/znr6s28ynr-maker/Deep-Learning-with-Python-Experimentation/blob/main/First_Steps_with_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
import numpy as np

train_images.shape

(60000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
test_images.shape

(10000, 28, 28)

In [ ]:
len(train_labels)

60000

In [ ]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [ ]:
#network architecture
import keras
from keras import layers

model = keras.Sequential(
    [layers.Dense(512, activation="relu"),
     layers.Dense(10, activation="softmax"),]
)

In [ ]:
#compilation step
model.compile(
    optimizer= "adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

In [ ]:
#preparing the image data
train_images = train_images.reshape(60000, 28 * 28)
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [ ]:
#fitting the model
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 8s 13ms/step - accuracy: 0.9218 - loss: 0.2706
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.9686 - loss: 0.1077
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 12s 19ms/step - accuracy: 0.9792 - loss: 0.0708
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - accuracy: 0.9859 - loss: 0.0490
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 9s 18ms/step - accuracy: 0.9897 - loss: 0.0359


In [ ]:
#using the model to make predictions. resulting array shows probabilities for each digit, starting at 0
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step


array([2.1514509e-06, 2.2716048e-08, 3.4469729e-05, 1.6469497e-04,
       3.9913766e-09, 1.6681719e-07, 1.2859382e-11, 9.9978709e-01,
       1.8932062e-06, 9.4600036e-06], dtype=float32)

In [ ]:
#highest predicted value
predictions[0].argmax()

np.int64(7)

In [ ]:
#percentage probability of predicted value
predictions[0][7]

np.float32(0.9997871)

In [ ]:
#checking to see what the tests labels say
test_labels[0]

np.uint8(7)

In [ ]:
#evaluating the model on new data
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9789 - loss: 0.0673
test_acc: 0.9789000153541565
